#!/usr/bin/env bash
set -o errexit
set -o nounset

readonly java_version=${1:-9}
readonly platform="linux-x64"
readonly destination=${2:-/usr/lib/java}

function die {
    echo "$*"
    exit 1
}

#
# Download JDK
#
echo "Looking for Java ${java_version} package"
readonly root_url='http://www.oracle.com'
readonly jdk_downloads_url=$(curl -Ls ${root_url}/technetwork/java/javase/downloads/index.html | egrep -om1 "\/technetwork\/java\/javase\/downloads\/jdk${java_version}-downloads-[0-9]+?\.html")
[[ -n "${jdk_downloads_url}" ]] || die "No downloads url found for Java ${java_version} on ${root_url}"
readonly jdk_package_url=$(curl -Ls ${root_url}${jdk_downloads_url} | tee /tmp/out.txt | egrep -o "http\:\/\/download\.oracle\.com\/otn-pub\/java\/jdk\/${java_version}.*?\/jdk-${java_version}.*?${platform}.*?\.tar\.gz")
[[ -n "${jdk_package_url}" ]] || die "No package url found for Java ${java_version} on ${jdk_downloads_url}"
readonly jdk_package_name=$(basename ${jdk_package_url})
echo "Downloading ${jdk_package_name}"
curl --progress-bar --location --cookie "oraclelicense=accept-securebackup-cookie" ${jdk_package_url} -o ${jdk_package_name}

#
# Unpack
#
echo
echo "Unpacking into ${destination}"
mkdir -p ${destination}
tar zxvf ${jdk_package_name} --no-same-owner --strip-components=1 -C ${destination}
rm ${jdk_package_name}

#
# Install
#
echo
echo "Installing Java ${java_version}"
for f in $(find ${destination}/bin -type f); do
    [[ -x $f ]] || continue
    cmd=$(basename ${f})
    update-alternatives --install "/usr/bin/${cmd}" "${cmd}" "${f}" 1
done

exit 0
