#!/usr/bin/env bash
set -o errexit
set -o nounset

readonly java_version=${1:-8}
readonly platform="linux-x64"
readonly destination=${2:-/usr/lib/java}

function die {
    echo "$*"
    exit 1
}

#
# Download JDK
#
echo "Looking for Java ${java_version} package"
readonly root_url='http://www.oracle.com'
readonly jdk_downloads_url=$(curl -s ${root_url}/technetwork/java/javase/downloads/index.html | egrep -om1 "/technetwork/java/javase/downloads/jdk${java_version}-downloads-.+?\.html")
[[ -n "${jdk_downloads_url}" ]] || die "No downloads url found for Java ${java_version} on ${root_url}"
readonly jdk_package_url=$(curl -s ${root_url}${jdk_downloads_url} | egrep -o "http\:\/\/download.oracle\.com/otn-pub/java/jdk/${java_version}u[0-9]+\-(.*)+\/jdk-${java_version}u[0-9]+(.*)${platform}.tar.gz")
[[ -n "${jdk_package_url}" ]] || die "No package url found for Java ${java_version} on ${jdk_downloads_url}"
readonly jdk_package_name=$(basename ${jdk_package_url})
echo "Downloading ${jdk_package_name}"
curl --progress-bar --location --cookie "oraclelicense=accept-securebackup-cookie" ${jdk_package_url} -o ${jdk_package_name}

#
# Download JCE
#
echo "Looking for JCE${java_version} package"
readonly jce_download_url=$(curl -s ${root_url}/technetwork/java/javase/downloads/index.html | egrep -om1 "/technetwork/java/javase/downloads/jce${java_version}-download-.+?\.html")
[[ -n "${jce_download_url}" ]] || die "No downloads url found for JCE${java_version} on ${root_url}"
readonly jce_package_url=$(curl -s ${root_url}${jce_download_url} | egrep -o "http\:\/\/download.oracle\.com/otn-pub/java/jce/[0-9]+/jce_policy-[0-9]+\.zip")
readonly jce_package_name=$(basename ${jce_package_url})
echo "Downloading ${jce_package_name}"
curl --progress-bar --location --cookie "oraclelicense=accept-securebackup-cookie" ${jce_package_url} -o ${jce_package_name}
[[ "$(file --brief --mime-type ${jce_package_name})" == "application/zip" ]] || die "Failed to download ${jce_package_name} (unexpected mime-type)"

#
# Unpack
#
echo
echo "Unpacking into ${destination}"
mkdir -p ${destination}
tar zxvf ${jdk_package_name} --no-same-owner --strip-components=1 -C ${destination}
rm ${jdk_package_name}
mkdir -p ${destination}/jre/lib/security
unzip -d ${destination}/jre/lib/security -j -o ${jce_package_name}
rm ${jce_package_name}

#
# Install
#
echo
echo "Installing Java ${java_version}"
for f in $(find ${destination}/bin -type f); do
    [[ -x $f ]] || continue
    cmd=$(basename ${f})
    update-alternatives --install "/usr/bin/${cmd}" "${cmd}" "${f}" 1
done

exit 0
